export const topics = [
  // { title: 'Values', status: null },
  // { title: 'Variables', status: null },
  // { title: 'Constants', status: null },
  // { title: 'For', status: null },
  // { title: 'If/Else', status: null },
  // { title: 'Switch', status: null },
  { title: 'Arrays', status: 'ok', path: '/go/arrays' },
  { title: 'Slices', status: 'ok', path: '/go/slices' },
  { title: 'Maps', status: 'ok', path: '/go/maps' },
  { title: 'Range', status: 'ok', path: '/go/range' },
  { title: 'Functions', status: 'ok', path: '/go/functions' },
  { title: 'Multiple Return Values', status: 'ok', path: '/go/multiple-return-values' },
  { title: 'Variadic Functions', status: 'ok', path: '/go/variadic-functions' },
  { title: 'Closures', status: 'ok', path: '/go/closures' },
  { title: 'Recursion', status: 'ok', path: '/go/recursion' },
  { title: 'Pointers', status: 'ok', path: '/go/pointers' },
  // { title: '', status: null },
]