export const topics = [
  // { title: 'Values', status: null },
  // { title: 'Variables', status: null },
  // { title: 'Constants', status: null },
  // { title: 'For', status: null },
  // { title: 'If/Else', status: null },
  // { title: 'Switch', status: null },
  { title: 'Arrays', status: 'ok' },
  { title: 'Slices', status: 'ok' },
  { title: 'Maps', status: 'ok' },
  { title: 'Range', status: 'ok' },
  { title: 'Functions', status: 'ok' },
  { title: 'Multiple Return Values', status: 'ok' },
  { title: 'Variadic Functions', status: null },
  { title: 'Closures', status: null },
  { title: 'Recursion', status: null },
  { title: 'Pointers', status: null },
  // { title: '', status: null },
]